### ISSUE TITLE
[New Tool] OpenSCA-cli

### ISSUE THREAD

**Issue by cyberchen1995** [interlynk-io/sbombenchmark.dev#16]
**Tool name and link (must be open source)**
OpenSCA-cli, https://github.com/XmirrorSecurity/OpenSCA-cli

**Supported specifications**
- [x] CycloneDX
- [x] SPDX

**Supported target**
- [ ] Container images
- [ ] Source code repositories
- [x] Packages

**Environment setup (if any)**
None

**Recommended command to see version**
(e.g. sartre-sbom --version --json)
opensca-cli -version

**Recommended command(s) to build SBOM**
(e.g. sartre-sbom build --cyclonedx --no-vuln ubuntu:latest)
opensca-cli -path ${project path} -out output.spdx.json
opensca-cli -path ${project path} -out output.cdx.json

**Additional context**
(e.g. only supports tag-value in SPDX, has external dependencies)

**Comment by surendrapathak** [comment]
Thanks for raising this @SuperChen-CC , Just a preliminary note that SBOMs generated with OpenSCA seem to be missing key details, such as 
- creator tool details: Missing from CycloneDX, Missing version in SPDX
- license details for packages
- checksums for packages

These are not blockers but lead to a low [sbomqs](https://github.com/interlynk-io/sbomqs) score. I am sharing examples of some scoring in case you plan to tackle these.


![Screenshot 2024-01-24 at 4 57 26 PM](https://github.com/interlynk-io/sbombenchmark.dev/assets/1686327/b5b81901-ad44-42a1-b5b0-8e1f8ee9016d)

![Screenshot 2024-01-24 at 4 57 43 PM](https://github.com/interlynk-io/sbombenchmark.dev/assets/1686327/6f89aaf5-8d64-4e82-9080-6bf8268db879)

sbomqs score output.cdx.json
SBOM Quality Score:4.8	components:408	output.cdx.json
+-----------------------+--------------------------------+-----------+--------------------------------+
|       CATEGORY        |            FEATURE             |   SCORE   |              DESC              |
+-----------------------+--------------------------------+-----------+--------------------------------+
| NTIA-minimum-elements | comp_with_name                 | 10.0/10.0 | 407/408 have names             |
+                       +--------------------------------+-----------+--------------------------------+
|                       | comp_with_supplier             | 0.0/10.0  | 0/408 have supplier names      |
+                       +--------------------------------+-----------+--------------------------------+
|                       | comp_with_uniq_ids             | 10.0/10.0 | 408/408 have unique ID's       |
+                       +--------------------------------+-----------+--------------------------------+
|                       | comp_with_version              | 9.9/10.0  | 402/408 have versions          |
+                       +--------------------------------+-----------+--------------------------------+
|                       | sbom_authors                   | 0.0/10.0  | doc has 0 authors              |
+                       +--------------------------------+-----------+--------------------------------+
|                       | sbom_creation_timestamp        | 0.0/10.0  | doc has creation timestamp     |
+                       +--------------------------------+-----------+--------------------------------+
|                       | sbom_dependencies              | 10.0/10.0 | doc has 367 relationships      |
+-----------------------+--------------------------------+-----------+--------------------------------+
| Quality               | comp_valid_licenses            | 0.0/10.0  | 0/408 components with valid    |
|                       |                                |           | license                        |
+                       +--------------------------------+-----------+--------------------------------+
|                       | comp_with_any_vuln_lookup_id   | 10.0/10.0 | 407/408 components have any    |
|                       |                                |           | lookup id                      |
+                       +--------------------------------+-----------+--------------------------------+
|                       | comp_with_deprecated_licenses  | 0.0/10.0  | no licenses found              |
+                       +--------------------------------+-----------+--------------------------------+
|                       | comp_with_multi_vuln_lookup_id | 0.0/10.0  | 0/408 components have multiple |
|                       |                                |           | lookup id                      |
+                       +--------------------------------+-----------+--------------------------------+
|                       | comp_with_primary_purpose      | 10.0/10.0 | 408/408 components have        |
|                       |                                |           | primary purpose specified      |
+                       +--------------------------------+-----------+--------------------------------+
|                       | comp_with_restrictive_licenses | 0.0/10.0  | no licenses found              |
+                       +--------------------------------+-----------+--------------------------------+
|                       | sbom_with_creator_and_version  | 0.0/10.0  | 0/0 tools have creator and     |
|                       |                                |           | version                        |
+                       +--------------------------------+-----------+--------------------------------+
|                       | sbom_with_primary_component    | 10.0/10.0 | primary component found        |
+-----------------------+--------------------------------+-----------+--------------------------------+
| Semantic              | comp_with_checksums            | 0.0/10.0  | 0/408 have checksums           |
+                       +--------------------------------+-----------+--------------------------------+
|                       | comp_with_licenses             | 0.0/10.0  | 0/408 have licenses            |
+                       +--------------------------------+-----------+--------------------------------+
|                       | sbom_required_fields           | 10.0/10.0 | Doc Fields:true Pkg            |
|                       |                                |           | Fields:false                   |
+-----------------------+--------------------------------+-----------+--------------------------------+
| Sharing               | sbom_sharable                  | 0.0/10.0  | doc has a sharable license     |
|                       |                                |           | free 0 :: of 0                 |
+-----------------------+--------------------------------+-----------+--------------------------------+
| Structural            | sbom_parsable                  | 10.0/10.0 | provided sbom is parsable      |
+                       +--------------------------------+-----------+--------------------------------+
|                       | sbom_spec                      | 10.0/10.0 | provided sbom is in a          |
|                       |                                |           | supported sbom format of       |
|                       |                                |           | spdx,cyclonedx                 |
+                       +--------------------------------+-----------+--------------------------------+
|                       | sbom_spec_file_format          | 10.0/10.0 | provided sbom should be in     |
|                       |                                |           | supported file format for      |
|                       |                                |           | spec: json and version:        |
|                       |                                |           | json,xml                       |
+                       +--------------------------------+-----------+--------------------------------+
|                       | sbom_spec_version              | 0.0/10.0  | provided sbom should be        |
|                       |                                |           | in supported spec version      |
|                       |                                |           | for spec:1.5 and versions:     |
|                       |                                |           | 1.0,1.1,1.2,1.3,1.4            |
+-----------------------+--------------------------------+-----------+--------------------------------+


sbomqs score output.spdx.json
SBOM Quality Score:4.9	components:814	output.spdx.json
+-----------------------+--------------------------------+-----------+--------------------------------+
|       CATEGORY        |            FEATURE             |   SCORE   |              DESC              |
+-----------------------+--------------------------------+-----------+--------------------------------+
| NTIA-minimum-elements | comp_with_name                 | 10.0/10.0 | 814/814 have names             |
+                       +--------------------------------+-----------+--------------------------------+
|                       | comp_with_supplier             | 1.6/10.0  | 132/814 have supplier names    |
+                       +--------------------------------+-----------+--------------------------------+
|                       | comp_with_uniq_ids             | 10.0/10.0 | 814/814 have unique ID's       |
+                       +--------------------------------+-----------+--------------------------------+
|                       | comp_with_version              | 10.0/10.0 | 814/814 have versions          |
+                       +--------------------------------+-----------+--------------------------------+
|                       | sbom_authors                   | 10.0/10.0 | doc has 1 authors              |
+                       +--------------------------------+-----------+--------------------------------+
|                       | sbom_creation_timestamp        | 10.0/10.0 | doc has creation timestamp     |
|                       |                                |           | 2024-01-24T16:51:47Z           |
+                       +--------------------------------+-----------+--------------------------------+
|                       | sbom_dependencies              | 10.0/10.0 | doc has 367 relationships      |
+-----------------------+--------------------------------+-----------+--------------------------------+
| Quality               | comp_valid_licenses            | 0.0/10.0  | 0/814 components with valid    |
|                       |                                |           | license                        |
+                       +--------------------------------+-----------+--------------------------------+
|                       | comp_with_any_vuln_lookup_id   | 10.0/10.0 | 814/814 components have any    |
|                       |                                |           | lookup id                      |
+                       +--------------------------------+-----------+--------------------------------+
|                       | comp_with_deprecated_licenses  | 0.0/10.0  | no licenses found              |
+                       +--------------------------------+-----------+--------------------------------+
|                       | comp_with_multi_vuln_lookup_id | 0.0/10.0  | 0/814 components have multiple |
|                       |                                |           | lookup id                      |
+                       +--------------------------------+-----------+--------------------------------+
|                       | comp_with_primary_purpose      | 0.0/10.0  | 0/814 components have primary  |
|                       |                                |           | purpose specified              |
+                       +--------------------------------+-----------+--------------------------------+
|                       | comp_with_restrictive_licenses | 0.0/10.0  | no licenses found              |
+                       +--------------------------------+-----------+--------------------------------+
|                       | sbom_with_creator_and_version  | 0.0/10.0  | 0/1 tools have creator and     |
|                       |                                |           | version                        |
+                       +--------------------------------+-----------+--------------------------------+
|                       | sbom_with_primary_component    | 0.0/10.0  | no primary component found     |
+-----------------------+--------------------------------+-----------+--------------------------------+
| Semantic              | comp_with_checksums            | 0.0/10.0  | 0/814 have checksums           |
+                       +--------------------------------+-----------+--------------------------------+
|                       | comp_with_licenses             | 0.0/10.0  | 0/814 have licenses            |
+                       +--------------------------------+-----------+--------------------------------+
|                       | sbom_required_fields           | 0.0/10.0  | Doc Fields:false Pkg           |
|                       |                                |           | Fields:false                   |
+-----------------------+--------------------------------+-----------+--------------------------------+
| Sharing               | sbom_sharable                  | 0.0/10.0  | doc has a sharable license     |
|                       |                                |           | free 0 :: of 0                 |
+-----------------------+--------------------------------+-----------+--------------------------------+
| Structural            | sbom_parsable                  | 10.0/10.0 | provided sbom is parsable      |
+                       +--------------------------------+-----------+--------------------------------+
|                       | sbom_spec                      | 10.0/10.0 | provided sbom is in a          |
|                       |                                |           | supported sbom format of       |
|                       |                                |           | spdx,cyclonedx                 |
+                       +--------------------------------+-----------+--------------------------------+
|                       | sbom_spec_file_format          | 10.0/10.0 | provided sbom should be in     |
|                       |                                |           | supported file format for      |
|                       |                                |           | spec: json and version:        |
|                       |                                |           | json,yaml,rdf,tag-value        |
+                       +--------------------------------+-----------+--------------------------------+
|                       | sbom_spec_version              | 10.0/10.0 | provided sbom should be in     |
|                       |                                |           | supported spec version for     |
|                       |                                |           | spec:SPDX-2.3 and versions:    |
|                       |                                |           | SPDX-2.1,SPDX-2.2,SPDX-2.3     |
+-----------------------+--------------------------------+-----------+--------------------------------+

**Comment by cyberchen1995** [comment]
Thanks for your suggestions, we will start to optimize these contents.

**Comment by surendrapathak** [comment]
<img width="1152" alt="Screenshot 2024-01-26 at 9 56 51 PM" src="https://github.com/interlynk-io/sbombenchmark.dev/assets/1686327/4989cd4a-2be3-4006-8897-5e97eed28c20">

Hi, @SuperChen-CC, sbombenchmark now has OpenSCA integrated with a handful of SBOM scanned. I understand that you are working on improving the SBOM capabilities of OpenSCA. So please let us know when they are completed, and we can -rescan all the repositories with it.

Related: I didn't see SBOM published for the OpenSCA project itself. Is this something you'd be interested in building? We can share some pointers on that.
