### ISSUE TITLE
Add a 'Add New Tool ' button for tool inclusion requests

### ISSUE THREAD

**Issue by surendrapathak** [interlynk-io/sbombenchmark.dev#4]
**Is your feature request related to a problem? Please describe.**
https://sbombenchmark.dev currently lists the most popular SBOM generators, but it is not a comprehensive list, and might not be aware of new SBOM generators being built.

**Describe the solution you'd like**
Add a button that allows users to submit a request for new SBOM generators.

**Describe alternatives you've considered**
Following this github repo

**Additional context**
N/A

**Comment by surendrapathak** [comment]
https://sbombenchmark.dev/

**Comment by riteshnoronha** [comment]
We should probably link to  https://github.com/interlynk-io/sbombenchmark.dev/issues/new/choose 
as the current redirect is confusing.
