### ISSUE TITLE
[New Tool] Include sbom4python

### ISSUE THREAD

**Issue by anthonyharrison** [interlynk-io/sbombenchmark.dev#7]
**Tool name and link (must be open source)**
sbom4python - https://pypi.org/project/sbom4python/

**Supported specifications**
- [X] CycloneDX
- [X] SPDX

**Supported target**
- [ ] Container images
- [ ] Source code repositories
- [X] Packages

**Environment setup (if any)**
Python module must be installed with its dependencies. e.g. pip install <python module name>

**Recommended command to see version**
sbom4python --version

**Recommended command(s) to build SBOM**
sbom4python --module <python module name>  --output-file <filename.spdx> - geneates SPDX SBOM in TagValue format. Output stored in specified filename

sbom4python --module <python module name> --format json --output-file <filename.spdx.json> - geneates SPDX SBOM in Json format. Output stored in specified filename

sbom4python --module <python module name> --sbom cyclonedx --format json --output-file <filename.json> - geneates Cyclonedx SBOM in Json format. Output stored in specified filename

**Additional context**
Supports tag value, Json, YAML for SPDX and JSON for CycloneDX

**Comment by surendrapathak** [comment]
Deployed.
